name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.8
  - menuinst
  - console_shortcut
  - powershell_shortcut
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2021.05=py38_0
  - anaconda-navigator==2.1.2
  - navigator-updater
prefix: C:\ProgramData\Anaconda3
